version: '3.8'
services:

  #
  # The web host simply serves static content
  #
  webhost:
    image: webhost:1.0.0
    hostname: webhost
    ports:
      - 443:3000
    volumes:
      - ./webhost/config.json:/usr/webhost/config.json
      - ./spa/config.json:/usr/webhost/content/config.json
      - ./certs/example.server.p12:/usr/webhost/certs/example.server.p12
    environment:
      NODE_ENV: 'production'

  #
  # Deploy the example business API, which is a simple API that just validates JWTs
  # It runs on port 3002 inside the cluster at https://api.internal-example.com:3002
  # The SPA accesses it via the reverse proxy at https://api.example.com:3000/api
  # The API calls the Authorization Server's JWKS endpoint inside the cluster
  #
  business-api:
    image: business-api:1.0.0
    hostname: api-${INTERNAL_DOMAIN}
    volumes:
      - ./api/config.json:/usr/api/config.json
      - ./certs/example.ca.pem:/usr/api/certs/example.ca.pem
      - ./certs/example.server.p12:/usr/api/certs/example.server.p12
    environment:
      NODE_EXTRA_CA_CERTS: '/usr/api/certs/example.ca.pem'

  #
  # The OAuth Agent provided by Curity is hosted here, to perform the OpenID Connect work
  # It runs on port 3001 inside the cluster at https://oauthagent.internal-example.com:3001
  # The SPA accesses it via the reverse proxy at https://api.example.com:3000/oauth-agent
  # The OAuth Agent calls the Authorization Server's token endpoint inside the cluster
  #
  oauth-agent:
    image: oauthagent-financial:1.0.0
    hostname: oauthagent-${INTERNAL_DOMAIN}
    volumes:
      - ./certs/example.ca.pem:/usr/api/certs/example.ca.pem
      - ./certs/example.client.p12:/usr/api/certs/example.client.p12
      - ./certs/example.server.p12:/usr/api/certs/example.server.p12
    environment:
      PORT: 3001
      SERVER_CERT_P12_PATH: './certs/example.server.p12'
      SERVER_CERT_P12_PASSWORD: 'Password1'
      CLIENT_CERT_P12_PATH: './certs/example.client.p12'
      CLIENT_CERT_P12_PASSWORD: 'Password1'
      CA_CERT_PEM_PATH: './certs/example.ca.pem'
      TRUSTED_WEB_ORIGIN: "https://${WEB_DOMAIN}"
      ISSUER: "${ISSUER_URI}"
      JWKS_URI: '${JWKS_ENDPOINT}'
      AUTHORIZE_ENDPOINT: '${AUTHORIZE_ENDPOINT}'
      AUTHORIZE_EXTERNAL_ENDPOINT: "${AUTHORIZE_EXTERNAL_ENDPOINT}"
      TOKEN_ENDPOINT: '${TOKEN_ENDPOINT}'
      LOGOUT_ENDPOINT: "${LOGOUT_ENDPOINT}"
      CLIENT_ID: 'spa-client'
      REDIRECT_URI: 'https://${WEB_DOMAIN}/'
      POST_LOGOUT_REDIRECT_URI: 'https://${WEB_DOMAIN}/'
      SCOPE: 'openid profile'
      COOKIE_DOMAIN: '${API_DOMAIN}'
      COOKIE_NAME_PREFIX: 'example'
      COOKIE_ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
    command: >
      sh -c "/usr/lib/jvm/zulu11-ca/bin/keytool -import -alias example.ca -cacerts -file /usr/api/certs/example.ca.pem -storepass changeit -noprompt &&
             su apiuser &&
             java -jar /usr/api/oauth-agent-0.0.1-SNAPSHOT.jar"
    
  #
  # The Kong reverse proxy exposes API endpoints to the browser at https://api.example.com:3000
  # The reverse proxy routes to the OAuth Agent and the business API inside the cluster
  #
  reverse-proxy:
    image: kong:2.6.0-alpine
    hostname: reverseproxy
    ports:
      - 3000:3000
    volumes:
      - ./reverse-proxy/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./kong-phantom-token-plugin/plugin:/usr/local/share/lua/5.1/kong/plugins/phantom-token
      - ./oauth-proxy-plugin/plugin/plugin.lua:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/access.lua
      - ./oauth-proxy-plugin/plugin/handler.lua:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/handler.lua
      - ./oauth-proxy-plugin/plugin/schema.lua:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/schema.lua
      - ./oauth-proxy-plugin/plugin/kong-oauth-proxy-1.0.0-1.rockspec:/usr/local/share/lua/5.1/kong/plugins/oauth-proxy/oauth-proxy-1.0.0-1.rockspec
      - ./certs/example.ca.pem:/usr/local/share/certs/example.ca.pem
      - ./certs/example.server.key:/usr/local/share/certs/example.server.key
      - ./certs/example.server.pem:/usr/local/share/certs/example.server.pem
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3000 ssl'
      KONG_SSL_CERT: '/usr/local/share/certs/example.server.pem'
      KONG_SSL_CERT_KEY: './usr/local/share/certs/example.server.key'
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: './usr/local/share/certs/example.ca.pem'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,oauth-proxy,phantom-token'

  #
  # A SQL database used by the Curity Identity Server
  #
  curity-data:
    image: postgres:13.2
    hostname: dbserver
    profiles:
      - WITH_IDSVR
    volumes:
      - ./idsvr/data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_DB: 'idsvr'

  #
  # A standalone instance of the Curity Identity Server
  #
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:6.7.0
    hostname: login-${INTERNAL_DOMAIN}
    ports:
      - 6749:6749
      - 8443:8443
    profiles:
      - WITH_IDSVR
    volumes:
      - ./idsvr/license.json:/opt/idsvr/etc/init/license/license.json
      - ./idsvr/config-backup.xml:/opt/idsvr/etc/init/config.xml
      - ./idsvr/log4j2.xml:/opt/idsvr/etc/log4j2.xml
    environment:
      PASSWORD: 'Password1'
      FINANCIAL_GRADE_CLIENT_CA: "${FINANCIAL_GRADE_CLIENT_CA}"
      IDSVR_BASE_URL: "${IDSVR_BASE_URL}"
      WEB_DOMAIN: "${WEB_DOMAIN}"
      BASE_DOMAIN: "${BASE_DOMAIN}"
